sudo: true

language: c

services:
- docker

env:
    global:
    - IMAGE_NAME="aparcar/openwrt-sdk:18.06-ar71xx"
    - OPENWRT_BRANCH="18.06"

before_script:
- docker pull "$IMAGE_NAME" || true

script:
- |
  cat <<EOF > feeds.conf.default
  src-git libremesh https://github.com/libremesh/lime-packages.git;$TRAVIS_BRANCH
  EOF
- docker run 
        -v "/output:/sdk/bin/packages/mips_24kc/libremesh"
        -v "$(pwd)/feeds.conf.default:/sdk/feeds.conf.default"
        "$IMAGE_NAME" /bin/bash -c
        "apt update -qq && apt install time -y && ./scripts/feeds update -a && ./scripts/feeds install -p libremesh -a && ./scripts/feeds uninstall tinc && make defconfig && make -j V=s"
