sudo: false
dist: trusty
notifications:
  email: false
language: c
cache:
  directories:
    - $HOME/sdk
addons:
  apt:
    packages:
      - subversion 
      - g++
      - zlib1g-dev
      - build-essential 
      - git 
      - python 
      - rsync 
      - man-db
      - libncurses5-dev 
      - gawk 
      - gettext 
      - unzip 
      - file 
      - libssl-dev 
      - sshpass
      - lua5.2
      - wget 
      - tree
      - zip
before_script:
  - ./.travis_do.sh setup_sdk
script:
  - ./.travis_do.sh build_packages
after_success:
  - ./.travis_do.sh upload_packages
env:
  - SDK_TARGET="ar71xx/generic"
  - SDK_TARGET="x86/64"
  - SDK_TARGET="ramips/rt305x"
  - SDK_TARGET="ramips/rt3883"
  - SDK_TARGET="ramips/mt7620"
  - SDK_TARGET="ramips/mt7621"
  - SDK_TARGET="ramips/mt76x8"
  - SDK_TARGET="lantiq/xrx200"
  - SDK_TARGET="lantiq/xway"
  - SDK_TARGET="x86/generic"
  - SDK_TARGET="x86/geode"
  - SDK_TARGET="ipq806x/generic"
  - SDK_TARGET="brcm2708/bcm2708"
  - SDK_TARGET="brcm2708/bcm2709"
  - SDK_TARGET="brcm2708/bcm2710"
  - SDK_TARGET="brcm47xx/mips74k"
  - SDK_TARGET="brcm63xx/smp"
  - SDK_TARGET="octeon/generic"
  - SDK_TARGET="sunxi/cortexa53"
  - SDK_TARGET="sunxi/cortexa7"
  - SDK_TARGET="sunxi/cortexa8"
  - SDK_TARGET="mediatek/32"
  - SDK_TARGET="armvirt/64"
    #  - SDK_TARGET="armvirt/32"
