sudo: true

language: c

services:
- docker

env:
    global:
    - IMAGE_NAME="aparcar/openwrt-sdk:18.06-ar71xx"
    - OPENWRT_BRANCH="18.06"

before_script:
- docker pull "$IMAGE_NAME" || true

script:
- |
  cat <<EOF > feeds.conf.default
  #src-git base https://github.com/openwrt/openwrt.git;$OPENWRT_BRANCH
  #src-git packages https://github.com/openwrt/packages.git;$OPENWRT_BRANCH
  #src-git luci https://github.com/openwrt/luci.git;$OPENWRT_BRANCH
  #src-git routing https://github.com/openwrt/routing.git;$OPENWRT_BRANCH
  src-git libremesh https://github.com/libremesh/lime-packages.git;$TRAVIS_BRANCH
  EOF
- docker run -v "/output:/sdk/bin/packages/mips_24kc/libremesh"
        "$IMAGE_NAME" /bin/bash -c
        "./scripts/feeds update -a && ./scripts/feeds install -p libremesh -a && make"
