sudo: false
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - subversion
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - gcc-multilib
    - flex
    - git-core
    - gettext
    - libssl-dev
    - libstdc++6
notifications:
  email: false
language: c
cache: ccache
install:
- cd $TRAVIS_BUILD_DIR
- rm -rf sdk
- git clone https://github.com/libremesh/lime-sdk.git sdk
- cd sdk
- ./cooker -d x86/generic || true
- sed 's|https://github.com/libremesh/lime-packages.git;develop|'$TRAVIS_BUILD_DIR'|g' feeds.conf.default > feeds.conf.default.local
script:
- cd $TRAVIS_BUILD_DIR/sdk
- ./cooker --flavor=lime_default -c x86/generic --profile=Generic
