sudo: false
dist: trusty
notifications:
  email: false
language: c
cache:
  directories:
    - $TRAVIS_BUILD_DIR/sdk
addons:
  apt:
    packages:
      - subversion 
      - g++
      - zlib1g-dev
      - build-essential 
      - git 
      - python 
      - rsync 
      - man-db
      - libncurses5-dev 
      - gawk 
      - gettext 
      - unzip 
      - file 
      - libssl-dev 
      - sshpass
      - lua5.2
      - wget 
      - tree
      - zip
install:
- git clone https://github.com/aparcar/lime-sdk.git sdk || true
- cd sdk
- git checkout develop && git pull
- sed 's|https://github.com/libremesh/lime-packages.git.*|'$TRAVIS_BUILD_DIR'|g' feeds.conf.github > feeds.conf.default.local
- sed -i 's|sdk_compile_repos.*|sdk_compile_repos="libremesh"|g' options.conf
- ./cooker -f -d $TARGET --sdk $IB_DOWNLOAD
script:
  - /$TRAVIS_BUILD_DIR/.travis_do.sh build
after_success:
  - /$TRAVIS_BUILD_DIR/.travis_do.sh upload
env:
  - TARGET="ar71xx/generic"
  - TARGET="x86/64" IB_DOWNLOAD="--ib"
    #  - TARGET="ramips/rt305x"
    #  - TARGET="ramips/rt3883"
    #  - TARGET="ramips/mt7620"
    #  - TARGET="ramips/mt7621"
    #  - TARGET="ramips/mt76x8"
    #  - TARGET="lantiq/xrx200"
    #  - TARGET="lantiq/xway"
    #  - TARGET="x86/generic"
    #  - TARGET="x86/geode"
    #  - TARGET="ipq806x/generic"
    #  - TARGET="brcm2708/bcm2708"
    #  - TARGET="brcm2708/bcm2709"
    #  - TARGET="brcm2708/bcm2710"
    #  - TARGET="brcm47xx/mips74k"
    #  - TARGET="brcm63xx/smp"
    #  - TARGET="octeon/generic"
    #  - TARGET="sunxi/cortexa53"
    #  - TARGET="sunxi/cortexa7"
    #  - TARGET="sunxi/cortexa8"
    #  - TARGET="mediatek/32"
    #  - TARGET="armvirt/64"
    #  - TARGET="armvirt/32"
