name: Build packages

on:
  release:
    types: [published]
  push:
    branches: [master]
    tags:
      - v*

jobs:
  build:
    name: Build ${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build packages
        uses: openwrt/gh-action-sdk@v1
        env:
          ARCH: "x86_64"
          FEEDNAME: "libremesh"
          IGNORE_ERRORS: "n m y"

      - name: Set package destination
        run: |
          export TAG=$(echo "${{ github.ref }}" | cut -d '/' -f 3-)
          echo "$TAG"
          echo "::set-env name=DEST_DIR::$TAG"

      - name: Upload packages to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: libremesh
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://images.aparcar.org
          SOURCE_DIR: bin/packages/x86_64/libremesh/
          DEST_DIR: ${{ env.DEST_DIR }}

